steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frispy/$BRANCH_NAME:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frispy/$BRANCH_NAME:$COMMIT_SHA']

  # Deploy container image to USA
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$_SERVICE_ID'
    - '--image'
    - 'gcr.io/$PROJECT_ID/frispy/$BRANCH_NAME:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--port'
    - '8000'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--concurrency=2'
    - '--max-instances=40'

  # Deploy container image to EU
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$_SERVICE_ID-eu'
    - '--image'
    - 'gcr.io/$PROJECT_ID/frispy/$BRANCH_NAME:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
    - '--allow-unauthenticated'
    - '--port'
    - '8000'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--concurrency=2'
    - '--max-instances=40'

images:
  - 'gcr.io/$PROJECT_ID/frispy/$BRANCH_NAME:$COMMIT_SHA'
