services:
  frispy-flight-api: 
    build: .
    image: techdisc/frispy-flight-api:latest
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
